if Vagrant::VERSION < "2.0.0"
  $stderr.puts "Must redirect to new repository for old Vagrant versions"
  Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
end

Vagrant.configure("2") do |config|
  # Parallels
  config.vm.box = "bento/ubuntu-16.04"
  # VirtualBox
  # config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  # config.vm.synced_folder "shared/", "/shared", create: true
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = false
  config.vagrant.sensitive = [ENV["DIT_MD_VPN_CERT_PASS"], ENV["DIT_MD_VPN_PASS"]]

  config.vm.define "ditvpn" do |server|
    # Parallels
    server.vm.provider "parallels" do |prl|
       prl.name = "DIT-VPN"
       prl.memory = 512
       prl.cpus = 1
    end
    # VirtualBox
    # server.vm.provider "virtualbox" do |vb|
    #   vb.customize ["modifyvm", :id, "--cpus", "1"]
    #   vb.name = "DIT-VPN"
    #   vb.memory = 512
    # end
    server.vm.hostname = "ditvpn"
    server.vm.provision :shell, path: "provision-fortigate", args: ENV['DIT_MD_VPN_USER'], env: {DIT_MD_VPN_USER:ENV['DIT_MD_VPN_USER'], DIT_MD_VPN_PASS:ENV['DIT_MD_VPN_PASS'], DIT_MD_VPN_CERT_PASS:ENV['DIT_MD_VPN_CERT_PASS']}
  end

  # config.trigger.after :up, :reload do |trigger|
    # trigger.info = "Init Fortigate VPN..."
    # trigger.run_remote = { inline: "/home/vagrant/vpn/startup_vpn.sh" }
  # end
end
